CREATE TABLE `Dashboard-Data-All_infos` (
	`id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`ID_Equipe` VARCHAR(37) NOT NULL, 
	`ID_Ligue` VARCHAR(7) NOT NULL, 
	`Saison` DECIMAL NOT NULL, 
	`Division` DECIMAL NOT NULL, 
	`Poule` VARCHAR(1) NOT NULL, 
	`Code` VARCHAR(11) NOT NULL, 
	`Montee` DECIMAL NOT NULL, 
	`Descente` DECIMAL NOT NULL, 
	`Lien_PDF` VARCHAR(82), 
	`MPG_ID` VARCHAR(16) NOT NULL, 
	`Nom_Equipe` VARCHAR(48) NOT NULL, 
	`ID_Joueur` VARCHAR(12) NOT NULL, 
	`Nom_Joueur` VARCHAR(14) NOT NULL, 
	`Prénom` VARCHAR(14) NOT NULL, 
	`Promo` VARCHAR(9) NOT NULL
);

CREATE TABLE `Dashboard-Data-Chatte` (
	`ID_Joueur` VARCHAR(12) NOT NULL, 
	`ID_Saison` VARCHAR(7) NOT NULL, 
	`CD_Stat` VARCHAR(12) NOT NULL, 
	`Modalité` DECIMAL NOT NULL, 
	`Proba` DECIMAL
);

CREATE TABLE `Dashboard-Data-Class` (
	`Classement` DECIMAL NOT NULL, 
	`ID_Joueur` VARCHAR(12) NOT NULL, 
	`ID_Ligue` VARCHAR(7) NOT NULL
);

CREATE TABLE `Dashboard-Data-CoachQuality` (
	`ID_Joueur` VARCHAR(12) NOT NULL, 
	`Joueur` VARCHAR(17) NOT NULL, 
	`Poste` VARCHAR(9) NOT NULL, 
	`Club` VARCHAR(13) NOT NULL, 
	`NB_Buts_Esperes` DECIMAL NOT NULL, 
	`NB_Buts_Marques` DECIMAL NOT NULL, 
	`Journée` DECIMAL NOT NULL, 
	`Saison` DECIMAL NOT NULL, 
	`ID_JF` VARCHAR(13) NOT NULL
);

CREATE TABLE `Dashboard-Data-Detail_Joueur` (
	`ID_Match` VARCHAR(16) NOT NULL, 
	`ID_Joueur` VARCHAR(12) NOT NULL, 
	`Division` VARCHAR(12) NOT NULL, 
	`Saison` DECIMAL NOT NULL, 
	`ID_Adv` VARCHAR(12) NOT NULL, 
	`ID_JF` VARCHAR(13) NOT NULL, 
	`Journée` VARCHAR(13) NOT NULL, 
	`Note` DECIMAL, 
	`Poste` DECIMAL NOT NULL, 
	`But` DECIMAL NOT NULL, 
	`MPG` DECIMAL NOT NULL, 
	`NoteBonus` DECIMAL, 
	`MJ` DECIMAL NOT NULL, 
	`Equipe` DECIMAL, 
	`Nom` VARCHAR(19) NOT NULL, 
	p VARCHAR(15)
);

CREATE TABLE `Dashboard-Data-Match` (
	`ID_Match` VARCHAR(16) NOT NULL, 
	`ID_Joueur` VARCHAR(12) NOT NULL, 
	`Division` DECIMAL NOT NULL, 
	`Saison` DECIMAL NOT NULL, 
	`ID_Adv` VARCHAR(12) NOT NULL, 
	`ID_Equipe` VARCHAR(37) NOT NULL, 
	`ID_Equipe_Adv` VARCHAR(37) NOT NULL, 
	`BM` DECIMAL NOT NULL, 
	`BP` DECIMAL NOT NULL, 
	`BM_MPG` DECIMAL NOT NULL, 
	`BP_MPG` DECIMAL NOT NULL, 
	`NB_Rotaldo` DECIMAL NOT NULL, 
	`NB_CSC_NoRotaldo` DECIMAL NOT NULL, 
	`NB_CSC_Rotaldo` DECIMAL NOT NULL, 
	`NB_Arret_Gardien` BOOL NOT NULL, 
	`NB_But_Arrete` BOOL NOT NULL, 
	`NB_But_Valise` BOOL NOT NULL, 
	`NB_But_Annule_Valise` BOOL NOT NULL, 
	`NB_Valise` BOOL NOT NULL, 
	`NB_Valise_contre` BOOL NOT NULL, 
	`NB_Zahia` BOOL NOT NULL, 
	`NB_Zahia_contre` BOOL NOT NULL, 
	`NB_Suarez` BOOL NOT NULL, 
	`NB_Suarez_contre` BOOL NOT NULL, 
	`NB_RB` BOOL NOT NULL, 
	`NB_RB_contre` BOOL NOT NULL, 
	`NB_Miroir` BOOL NOT NULL, 
	`NB_Miroir_contre` BOOL NOT NULL, 
	`Score_Valise` DECIMAL NOT NULL, 
	`Compo` DECIMAL NOT NULL, 
	`Compo_Adv` DECIMAL NOT NULL, 
	`isDom` BOOL NOT NULL, 
	`Journée` DECIMAL NOT NULL, 
	`Valise` DECIMAL NOT NULL, 
	`Zahia` DECIMAL NOT NULL, 
	`Suarez` DECIMAL NOT NULL, 
	`RB` DECIMAL NOT NULL, 
	`Miroir` DECIMAL NOT NULL, 
	`Valise Adv` DECIMAL NOT NULL, 
	`Zahia Adv` DECIMAL NOT NULL, 
	`Suarez Adv` DECIMAL NOT NULL, 
	`RB Adv` DECIMAL NOT NULL, 
	`Miroir Adv` DECIMAL NOT NULL, 
	`G` BOOL NOT NULL, 
	`N` BOOL NOT NULL, 
	`P` BOOL NOT NULL, 
	`Diff` DECIMAL NOT NULL, 
	`Score Victime` DECIMAL NOT NULL, 
	`MJ` BOOL NOT NULL, 
	CHECK (`NB_Arret_Gardien` IN (0, 1)), 
	CHECK (`NB_But_Arrete` IN (0, 1)), 
	CHECK (`NB_But_Valise` IN (0, 1)), 
	CHECK (`NB_But_Annule_Valise` IN (0, 1)), 
	CHECK (`NB_Valise` IN (0, 1)), 
	CHECK (`NB_Valise_contre` IN (0, 1)), 
	CHECK (`NB_Zahia` IN (0, 1)), 
	CHECK (`NB_Zahia_contre` IN (0, 1)), 
	CHECK (`NB_Suarez` IN (0, 1)), 
	CHECK (`NB_Suarez_contre` IN (0, 1)), 
	CHECK (`NB_RB` IN (0, 1)), 
	CHECK (`NB_RB_contre` IN (0, 1)), 
	CHECK (`NB_Miroir` IN (0, 1)), 
	CHECK (`NB_Miroir_contre` IN (0, 1)), 
	CHECK (`isDom` IN (0, 1)), 
	CHECK (`G` IN (0, 1)), 
	CHECK (`N` IN (0, 1)), 
	CHECK (`P` IN (0, 1)), 
	CHECK (`MJ` IN (0, 1))
);

CREATE TABLE `Dashboard-Data-Mercato` (
	`ID_Joueur` VARCHAR(12) NOT NULL, 
	`Division` DECIMAL NOT NULL, 
	`Saison` VARCHAR(9) NOT NULL, 
	`ID_JF` VARCHAR(13) NOT NULL, 
	`Joueur` VARCHAR(19) NOT NULL, 
	`Poste` VARCHAR(9) NOT NULL, 
	`Club` VARCHAR(11) NOT NULL, 
	`Prix` DECIMAL NOT NULL
);

CREATE TABLE `Dashboard-Data-Records` (
	`ID_Record` VARCHAR(21) NOT NULL, 
	`ID_Joueur` VARCHAR(12), 
	`Nom` VARCHAR(14) NOT NULL, 
	`Prénom` VARCHAR(14) NOT NULL, 
	`Date` VARCHAR(22), 
	`Classement` DECIMAL NOT NULL, 
	`MJ` DECIMAL, 
	`PTS` DECIMAL, 
	`G` DECIMAL, 
	`N` DECIMAL, 
	`P` DECIMAL, 
	`BM` DECIMAL, 
	`BP` DECIMAL, 
	`BM_MPG` DECIMAL, 
	`BP_MPG` DECIMAL, 
	`Note` DECIMAL, 
	`NoteBonus` DECIMAL, 
	`Chatte` DECIMAL, 
	`Diff` DECIMAL, 
	`Série` DECIMAL, 
	`NB_Saison` DECIMAL, 
	`ID_Adv` VARCHAR(12), 
	`Nom_Adv` VARCHAR(12), 
	`Prénom_Adv` VARCHAR(14), 
	`Joueur` VARCHAR(13), 
	`Prix` DECIMAL, 
	`Jungle` DECIMAL, 
	`Rotaldo` DECIMAL, 
	`Petro-Green` DECIMAL, 
	`Position` DECIMAL, 
	`Nom Joueur Foot` VARCHAR(13), 
	`Victime` DECIMAL, 
	`NB_Valise` DECIMAL, 
	`NB_Zahia` DECIMAL, 
	`NB_Suarez` DECIMAL, 
	`NB_RB` DECIMAL, 
	`NB_Miroir` DECIMAL, 
	`ID_Match` VARCHAR(11), 
	`Saison` DECIMAL
);

CREATE TABLE `Dashboard-Data-Series` (
	`ID_Joueur` VARCHAR(12) NOT NULL, 
	`Date_Debut` VARCHAR(6) NOT NULL, 
	`Date_Fin` VARCHAR(6) NOT NULL, 
	`NB` DECIMAL NOT NULL, 
	`Quoi` VARCHAR(1) NOT NULL
);
